spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sql3.freesqldatabase.com:3306/ferreyrabd
    username: ferreyra
    password: Jrboca97@
    show-sql: true
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    showl-sql: true


